name: Deploy Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run:
          docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Tag Docker image
        run:
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
          ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run:
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:latest
